# Generated by Django 4.1.5 on 2023-02-27 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments_post_comments_pub_date_posts_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 18, 20, 51, 869043)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 18, 20, 51, 867980)),
        ),
    ]
