# Generated by Django 4.1.5 on 2023-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_text_id_alter_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
